sudo: required

language: java

matrix:
    include:
        - os: linux
          jdk: oraclejdk7
          env: jdk=travis/oraclejdk7 override_jdk=false
            
        - os: linux
          jdk: "openjdk7"
          env: jdk=travis/openjdk7 override_jdk=false
          
        - os: linux
          jdk: oraclejdk8
          env: jdk=travis/oraclejdk8 override_jdk=false
        
        - os: linux
          language: generic
          env: jdk=oraclejdk8 override_jdk=true
        
        - os: linux
          language: generic
          env: jdk=openjdk8 override_jdk=true        
        
before_install:
  - if [['$jdk' == 'openjdk8']]; then sudo add-apt-repository ppa:openjdk-r/ppa -y; fi  
  - if [['$jdk' == 'oraclejdk8']]; then sudo add-apt-repository ppa:webupd8team/java -y; fi
  - if [['$override_jdk' == 'true']]; then sudo apt-get update -qq -y; fi 

install:   
  - if [['$jdk' == 'openjdk8']]; then sudo apt-get install openjdk-8 openjfx -y; fi  
  - if [['$jdk' == 'oraclejdk8']]; then sudo apt-get install --no-install-recommends oracle-java8-installer -y; fi
  - if [['$override_jdk' == 'true']]; then jdkswitcher use $jdk_target && jdkswitcher home; fi

before_script:
  - git submodule update --init --recursive

script:
  - mvn clean install -DskipTests=true -Dgpg.skip=true
  - mvn clean test -Dgpg.skip=true

cache:
  directories:
  - ${HOME}/.m2
