language: bash

sudo: required 

services:
  - docker 

env:
  - DESIRED_MAVEN_VERSION=3.3.9
  - RUN_IMAGE=emabrey-parent/emabrey-default-maven-image:maven-${DESIRED_MAVEN_VERSION}_openjdk-8
  - RUN_ID=emabrey_maven
  - EXECUTE_IN_DOCKER=docker exec -it ${RUN_ID}
    
cache:
  directories:
    - ${HOME}/.m2

before_install:
  - git submodule update --init --recursive 
  - docker build –-build-arg MAVEN_VERSION=${DESIRED_MAVEN_VERSION} -t ${RUN_IMAGE} .
    
install:  
  - docker run -it --name ${RUN_ID} -v ${HOME}/.m2:/root/.m2 -v $(pwd):/root/sources -w /root/sources ${RUN_IMAGE}
    
script:
  - $EXECUTE_IN_DOCKER mvn clean install -DskipTests=true -Dgpg.skip=true
  - $EXECUTE_IN_DOCKER mvn clean test -Dgpg.skip=true
  
after_script:
  - docker stop ${RUN_ID}
  - docker rm --force ${RUN_ID}
 