language: java

sudo: required

services:
- docker

cache:
  directories:
  - ${HOME}/.m2

before_install:
- git submodule update --init --recursive
- docker build -t emabrey-parent/emabrey-default-maven-image:maven-3.3.9_openjdk-8 .

install:
- docker run -it --name travis-build -v ${HOME}/.m2:/root/.m2 -v $(pwd):/root/sources -w /root/sources emabrey-parent/emabrey-default-maven-image:maven-3.3.9_openjdk-8

script:
- docker exec -it travis-build mvn clean install -DskipTests=true -Dgpg.skip=true
- docker exec -it travis-build mvn clean test -Dgpg.skip=true

after_script:
- docker stop travis-build
- docker rm --force travis-build